wzieba/Firebase-Distribution-Github-Action@v1

diff --git a/.github/workflows/deploy-cd.yml b/.github/workflows/deploy-cd.yml
--- a/.github/workflows/deploy-cd.yml
+++ b/.github/workflows/deploy-cd.yml
@@ -49,19 +49,28 @@ jobs:
           ls -R deploy_output
 
 
-      # Install Firebase CLI globally
-      - name: Install Firebase CLI Globally
-        run: |
-          curl -sL https://firebase.tools | bash
+      - name: Deploy to Firebase App Distribution
+        uses: wzieba/Firebase-Distribution-Github-Action@v1
+        with:
+          appId: ${{ secrets.FIREBASE_APP_ID }}
+          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
+          groups: ${{ secrets.FIREBASE_TESTER_GROUPS }}
+          file: deploy_output/app-release.apk
 
-      - name: Authenticate Firebase CLI
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
-        run: |
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase_key.json
-          export GOOGLE_APPLICATION_CREDENTIALS=firebase_key.json
-          firebase projects:list || echo "Warning: Authentication failed, but proceeding anyway"  # Verify authentication
-        continue-on-error: true
+
+#      # Install Firebase CLI globally
+#      - name: Install Firebase CLI Globally
+#        run: |
+#          curl -sL https://firebase.tools | bash
+#
+#      - name: Authenticate Firebase CLI
+#        env:
+#          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
+#        run: |
+#          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase_key.json
+#          export GOOGLE_APPLICATION_CREDENTIALS=firebase_key.json
+#          firebase projects:list || echo "Warning: Authentication failed, but proceeding anyway"  # Verify authentication
+#        continue-on-error: true
 
 
 #
@@ -84,11 +93,11 @@ jobs:
       # Step 9: Upload APK to Firebase App Distribution
       # Deploys the APK to Firebase, using app ID and tester groups stored as secrets
       # https://firebase.google.com/docs/app-distribution/android/distribute-cli
-      - name: Upload APK to Firebase App Distribution
-        run: |
-          firebase appdistribution:distribute deploy_output/app-release.apk \
-          --app ${{ secrets.FIREBASE_APP_ID }} \
-          --groups ${{ secrets.FIREBASE_TESTER_GROUPS }}
+#      - name: Upload APK to Firebase App Distribution
+#        run: |
+#          firebase appdistribution:distribute deploy_output/app-release.apk \
+#          --app ${{ secrets.FIREBASE_APP_ID }} \
+#          --groups ${{ secrets.FIREBASE_TESTER_GROUPS }}
 
       # Optional: Debug Firebase CLI output
       - name: Debug Firebase Output
